server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000
    
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///jtsys?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: admin
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
    
mybatis-plus:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mybatis/mappers/*.xml
  
logging:
  level:
    root: info
    com.sdh.my.blog: DEBUG
  #日志文件保存路径
  file: log/blog.log